language: node_js
node_js:
  - node
services:
  - docker
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Repo for yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - sleep 3
  # Updating NPM to relevant version >= 3 on Node.JS LTS
  - npm i -g npm@^3
  - npm install -g firebase-tools
install:
  - yarn
script:
  - npm test
  - npm run build:dev
  - firebase use --token $FIREBASE_DEPLOY_TOKEN $FIREBASE_PROJECT_DEV
  - firebase deploy --token $FIREBASE_DEPLOY_TOKEN -m "ci $TRAVIS_BRANCH build \#$TRAVIS_BUILD_NUMBER" --non-interactive
cache:
  directories:
  - $HOME/.yarn-cache
sudo: required
